server:
  port: 9002
spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
